---

- name: install dependencies
  include: depend.yml

- name: install haproxy exporter
  include: install.yml

- name: setup haproxy exporter as runit service and start it
  runit:
    name: "{{ prometheus_exporter_haproxy_service_name }}"
    enabled: true
    state: up
    timeout: 9
    user: "{{ prometheus_exporter_haproxy_user }}"
    command: "{{ prometheus_exporter_haproxy_install_dir }}/node_exporter collectors.enabled=attributes,diskstats,filesystem,loadavg,meminfo,stat,textfile,time,netdev,netstat,runit,lastlogin"

