---
# handlers file for prometheus_exporter_haproxy

- name: restart prometheus haproxy
  runit:
    name={{ prometheus_haproxy_service_name }}
    action=restart
    state=up
    enabled=true
    timeout=9
  when: not prometheus_haproxy_service_status.restarted

